### ISSUE TITLE
Shouldn't treat the parameters in nested functions as dependencies

### ISSUE THREAD

**Issue by linanqiu** [ColumbiaJS/hw3#7]
I'm failing this test case

``` js
it('shouldn\'t treat the parameters in nested functions as dependencies',
      function () {
        var injectedFuncWithNested = app.inject(function (app, login, Auth) {
          function nested(d, e, f) {}
          var args = Array.prototype.slice.call(arguments, 0);
          return args.length;
        });
        expect(injectedFuncWithNested()).to.equal(3);
      });
```

I'm confused by `app` and `login`. They were never registered with the module, so how can they be used in the function during injection? If they should be ignored, then why would `expect(injectedFunWithNested())).to.equal(3)`?

**Comment by levbrie** [comment]
@linanqiu really good question.  Actually, another student had the very same one.  Please see [issue 32 on js-course](https://github.com/ColumbiaJS/js-course/issues/32) and let me know if that discussion clears things up for you.   

Best,
Lev
